### ISSUE TITLE
About Downloading Videos from Huggingface

### ISSUE THREAD

**Issue by ruili33** [Share14/ShareGemini#2]
Thank you for your great work! We are planing to download the Webvid-2M dataset. However, we cannot figure out how to link the video to the Webvid-2M by either id or video column. Can you kindly give us some instruction on how to locate the right video in the Webvid-2M dataset?

Thank you very much!

**Comment by Share14** [comment]
Hi, we have upload a [file](https://huggingface.co/datasets/Share14/ShareGemini/blob/main/webvid_videoname2id.json) of mapping between id and filename for webvid videos.

**Comment by ruili33** [comment]
Thanks!
